version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    networks:
      - todo-network
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d tasksdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    # image: ghcr.io/navesedu/ks-docker:main
    container_name: todo_api
    networks:
      - todo-network
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tasksdb
      DB_USER: myuser
      DB_PASS: mypass
    depends_on:
      db:
        condition: service_healthy

networks:
  todo-network:
    driver: bridge

volumes:
  postgres_data: